import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import AuthProvider from "./auth/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

// poppins from google
const poppin = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300"],
});

// const poppins = localFont({
//   src: "",
//   variable: "--font-poppins",
//}); // then we go change the theme->extend in tailwind.config.ts

export const metadata: Metadata = {
  title: "Next Fundamentals",
  description: "Generated by create next app",
  openGraph: {
    title: "...",
    description: "...",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={poppin.className}>
        {/* <body className={poppin.variable}> */}
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
